require 'user.options'
require 'user.plugins'
require 'user.comment'
require 'user.colorscheme'
require 'user.cmp'
require 'user.lsp'
require 'user.dap'
require 'user.treesitter'
require 'user.telescope'
require 'user.gitsigns'
require 'user.indent_blankline'
require 'user.toggleterm'
require 'user.nvim-tree'

-- vim: ts=2 sts=2 sw=2 et
